### ISSUE TITLE
Crash In Bootup

### ISSUE THREAD

**Issue by PolarCoords** [Kaydax/Chikara#6]
When I drag a file on it, It doesn't work. I used a older version but i got a blank window...

**Comment by Kaydax** [comment]
What are your pc specs?

**Comment by PolarCoords** [comment]
CPU: Intel Pentium 1.60 Ghz 

RAM: 4 GB

**Comment by Kaydax** [comment]
And what gpu do you have?

**Comment by PolarCoords** [comment]
None it not come yet :/

**Comment by Kaydax** [comment]
The issue is the fact that your specs are too low end for Chikara to work on. If you are also unable to launch the newer versions of Chikara, that means you don't have AVX support. And since you told me you are using an older version, it seems that is the case. Also since you only have a Pentium that doesn't support AVX, I also assume you have no Vulkan support, so the crash makes sense since you don't support the graphics API that we use for the application. Chikara requires at least a dedicated GPU that supports Vulkan 1.0 with Geometry Shaders and a CPU that supports the AVX instruction set
